#include <errno.h>

static struct strerror {
	int num;
	const char *name;
	const char *description;
} strerrors[] = {
	{ EPERM, "EPERM", "Operation not permitted" },
	{ ENOENT, "ENOENT", "No such file or directory" },
	{ ESRCH, "ESRCH", "No such process" },
	{ EINTR, "EINTR", "Interrupted system call" },
	{ EIO, "EIO", "I/O error" },
	{ ENXIO, "ENXIO", "No such device or address" },
	{ E2BIG, "E2BIG", "Argument list too long" },
	{ ENOEXEC, "ENOEXEC", "Exec format error" },
	{ EBADF, "EBADF", "Bad file number" },
	{ ECHILD, "ECHILD", "No child processes" },
	{ EAGAIN, "EAGAIN", "Try again" },
	{ ENOMEM, "ENOMEM", "Out of memory" },
	{ EACCES, "EACCES", "Permission denied" },
	{ EFAULT, "EFAULT", "Bad address" },
	{ ENOTBLK, "ENOTBLK", "Block device required" },
	{ EBUSY, "EBUSY", "Device or resource busy" },
	{ EEXIST, "EEXIST", "File exists" },
	{ EXDEV, "EXDEV", "Cross-device link" },
	{ ENODEV, "ENODEV", "No such device" },
	{ ENOTDIR, "ENOTDIR", "Not a directory" },
	{ EISDIR, "EISDIR", "Is a directory" },
	{ EINVAL, "EINVAL", "Invalid argument" },
	{ ENFILE, "ENFILE", "File table overflow" },
	{ EMFILE, "EMFILE", "Too many open files" },
	{ ENOTTY, "ENOTTY", "Not a typewriter" },
	{ ETXTBSY, "ETXTBSY", "Text file busy" },
	{ EFBIG, "EFBIG", "File too large" },
	{ ENOSPC, "ENOSPC", "No space left on device" },
	{ ESPIPE, "ESPIPE", "Illegal seek" },
	{ EROFS, "EROFS", "Read-only file system" },
	{ EMLINK, "EMLINK", "Too many links" },
	{ EPIPE, "EPIPE", "Broken pipe" },
	{ EDOM, "EDOM", "Math argument out of domain of func" },
	{ ERANGE, "ERANGE", "Math result not representable" },
	{ EDEADLK, "EDEADLK", "Resource deadlock would occur" },
	{ ENAMETOOLONG, "ENAMETOOLONG", "File name too long" },
	{ ENOLCK, "ENOLCK", "No record locks available" },
	{ ENOSYS, "ENOSYS", "Function not implemented" },
	{ ENOTEMPTY, "ENOTEMPTY", "Directory not empty" },
	{ ELOOP, "ELOOP", "Too many symbolic links encountered" },
	{ EWOULDBLOCK, "EWOULDBLOCK", "Operation would block" },
	{ ENOMSG, "ENOMSG", "No message of desired type" },
	{ EIDRM, "EIDRM", "Identifier removed" },
	{ ECHRNG, "ECHRNG", "Channel number out of range" },
	{ EL2NSYNC, "EL2NSYNC", "Level 2 not synchronized" },
	{ EL3HLT, "EL3HLT", "Level 3 halted" },
	{ EL3RST, "EL3RST", "Level 3 reset" },
	{ ELNRNG, "ELNRNG", "Link number out of range" },
	{ EUNATCH, "EUNATCH", "Protocol driver not attached" },
	{ ENOCSI, "ENOCSI", "No CSI structure available" },
	{ EL2HLT, "EL2HLT", "Level 2 halted" },
	{ EBADE, "EBADE", "Invalid exchange" },
	{ EBADR, "EBADR", "Invalid request descriptor" },
	{ EXFULL, "EXFULL", "Exchange full" },
	{ ENOANO, "ENOANO", "No anode" },
	{ EBADRQC, "EBADRQC", "Invalid request code" },
	{ EBADSLT, "EBADSLT", "Invalid slot" },
	{ 0, 0, 0 }
};
