#!/bin/sh
#
#  Copyright (C) 2019 James Larrowe
#
#  This file is part of Minilibc.
#
#  Minilibc is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Minilibc is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with Minilibc.  If not, see <https://www.gnu.org/licenses/>.
#

SYSROOT="${MINISYSROOT}/usr"

if { echo "$@" | grep -e "-c" >/dev/null; } || \
   { echo "$@" | grep -e "-S" >/dev/null; } || \
   { echo "$@" | grep -e "-E" >/dev/null; } || \
   { echo "$@" | grep -e "-nostdlib" >/dev/null; }; then
  NOLIBS=1
fi

if { echo "$@" | grep -i -e "-fpic" >/dev/null; }; then
  PIC="S"
fi

NOLIBS_GCC="gcc --sysroot=${SYSROOT} -I${SYSROOT}/include"
LIBS_GCC="${NOLIBS_GCC} -nostdlib -L${SYSROOT}/lib ${SYSROOT}/lib/${PIC}crt1.o ${SYSROOT}/lib/crti.o"
END_LIBS="${SYSROOT}/lib/crtn.o"

if [ "${NOLIBS}" == 1 ]; then
  exec ${NOLIBS_GCC} "$@"
else
  exec ${LIBS_GCC} "$@" -lc "${END_LIBS}"
fi
