#!/bin/sh

SYSROOT="${MINISYSROOT}/usr"

if { echo "$@" | grep -e "-c" >/dev/null; } || \
   { echo "$@" | grep -e "-S" >/dev/null; } || \
   { echo "$@" | grep -e "-E" >/dev/null; } || \
   { echo "$@" | grep -e "-nostdlib" >/dev/null; }; then
  NOLIBS=1
fi

if { echo "$@" | grep -i -e "-fpic" >/dev/null; }; then
  PIC="S"
fi

NOLIBS_GCC="gcc --sysroot=${SYSROOT} -nostdinc -isystem${SYSROOT}/include"
LIBS_GCC="${NOLIBS_GCC} -nostdlib -L${SYSROOT}/lib ${SYSROOT}/lib/${PIC}crt1.o ${SYSROOT}/lib/crti.o"
END_LIBS="${SYSROOT}/lib/crtn.o"

if [ "${NOLIBS}" == 1 ]; then
  exec ${NOLIBS_GCC} "$@"
else
  exec ${LIBS_GCC} "$@" -lc "${END_LIBS}"
fi
